### ISSUE TITLE
figure 3 misconceptions

### ISSUE THREAD

**Issue by apetersson** [chainpoint/chainpoint#10]
just looked over it. i think some of the red circles need to be moved to the left in the whitepaper to produce the correct proof.

https://github.com/chainpoint/whitepaper/blob/master/chainpoint_white_paper.pdf

**Comment by super3** [comment]
Figure 2 is also incorrect, and not a valid Merkle tree.

@waynevaughan See https://en.wikipedia.org/wiki/Merkle_tree
I did a bad job of explaining Merkle trees. Each level up has n^2 leaves. Please update Figure 2&3.

**Comment by waynevaughan** [comment]
@apetersson In my haste to [re-illustrate the diagrams](https://github.com/chainpoint/whitepaper/commit/77837faa864bcda47b5b8a5de3887eb1788328e4) I inserted an extra row in the tree. I've fixed the tree and it's now showing the correct path.
